# Stage 1
FROM alpine:latest AS build

# Install dependencies
RUN apk add --update --no-cache npm hugo

RUN hugo version

WORKDIR /opt/app

COPY . .

# install node dependencies
RUN npm ci

EXPOSE 1313/tcp

CMD ["hugo", "server"]